In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("employee_data.csv")
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,E101,Aarav,IT,25,60000,2,Pune,3
1,E102,Diya,HR,29,50000,4,Mumbai,4
2,E103,Rohan,Finance,35,75000,8,Delhi,5
3,E104,Meera,IT,28,62000,3,Pune,4
4,E105,Kabir,Marketing,32,58000,6,Bangalore,3
5,E106,Isha,Finance,41,82000,12,Mumbai,5
6,E107,Arjun,IT,30,67000,5,Hyderabad,4
7,E108,Sara,HR,26,48000,2,Pune,3
8,E109,Vivaan,Marketing,38,73000,10,Delhi,5
9,E110,Anaya,Finance,27,69000,4,Mumbai,4
10,E111,Reyansh,IT,33,71000,7,Bangalore,5
11,E112,Myra,HR,31,52000,6,Hyderabad,4
12,E113,Krishna,Marketing,29,60000,5,Pune,3
13,E114,Aadhya,Finance,36,78000,9,Delhi,5
14,E115,Advait,IT,24,55000,1,Mumbai,3
15,E116,Siya,HR,34,54000,7,Bangalore,4
16,E117,Rudra,Marketing,40,76000,11,Hyderabad,5
17,E118,Anvi,Finance,28,70000,4,Pune,4
18,E119,Veer,IT,37,85000,10,Delhi,5
19,E120,Pari,HR,27,51000,3,Mumbai,3
20,E121,Daksh,Marketing,31,64000,6,Bangalore,4
21,E122,Kiara,Finance,39,88000,13,Hyderabad,5
22,E123,Yuvaan,IT,26,59000,3,Pune,3
23,E124,Saanvi,HR,30,53000,5,Delhi,4
24,E125,Ivaan,Marketing,33,72000,8,Mumbai,4
25,E126,Navya,Finance,42,90000,15,Bangalore,5
26,E127,Vihaan,IT,29,61000,4,Hyderabad,4
27,E128,Prisha,HR,35,56000,8,Pune,4
28,E129,Ayaan,Marketing,28,63000,5,Delhi,3
29,E130,Tara,Finance,37,84000,11,Mumbai,5

### **1. Dataset Overview**

In [5]:
df.head()
# gives us the first 5 rows of dataset by defualt can be assigned whichever number of rows we want ex : df.head(3)

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,E101,Aarav,IT,25,60000,2,Pune,3
1,E102,Diya,HR,29,50000,4,Mumbai,4
2,E103,Rohan,Finance,35,75000,8,Delhi,5
3,E104,Meera,IT,28,62000,3,Pune,4
4,E105,Kabir,Marketing,32,58000,6,Bangalore,3

In [7]:
df.head(3) #assigns us only the first 3 rows

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,E101,Aarav,IT,25,60000,2,Pune,3
1,E102,Diya,HR,29,50000,4,Mumbai,4
2,E103,Rohan,Finance,35,75000,8,Delhi,5

In [8]:
df.describe()
# count : gives us total number of values that column has so we have a dataset of 30 values/rows so we get count same for all columns as 30.
# mean : then we get the average/mean of age , avg salary , avg experience of people working in that company and avg performance score.
# std : this tells is the standard deviation of

             Age        Salary  Experience  PerformanceScore
count  30.000000     30.000000   30.000000         30.000000
mean   32.000000  66200.000000    6.566667          4.066667
std     5.051459  12084.187445    3.549486          0.784915
min    24.000000  48000.000000    1.000000          3.000000
25%    28.000000  56500.000000    4.000000          3.250000
50%    31.000000  63500.000000    6.000000          4.000000
75%    35.750000  74500.000000    8.750000          5.000000
max    42.000000  90000.000000   15.000000          5.000000